apiVersion: v1
kind: Secret
metadata:
  name: paperless-secret
  namespace: paperless-lab
type: Opaque
data:
  PAPERLESS_DBUSER: cGFwZXJsZXNz
  PAPERLESS_DBPASS: cGFwZXJsZXNzLWxhYi1wdw==
  PAPERLESS_SECRET_KEY: bGFiLXNlY3JldC1rZXktY2hhbmdlLW1l
  PAPERLESS_ADMIN_USER: YWRtaW4=
  PAPERLESS_ADMIN_PASSWORD: YWRtaW4tbGFiLXB3
