apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: mytravels-default
  labels:
    app: api
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
    - name: http
      port: 5101
      targetPort: 5101
      protocol: TCP
