apiVersion: v1
kind: Service
metadata:
  name: paperless
  namespace: paperless-lab
  labels:
    app: paperless
spec:
  type: ClusterIP
  selector:
    app: paperless
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
