# TODO: add argocd.argoproj.io/sync-wave: "1" under metadata on BOTH PVCs
# below (see secret.yaml in this folder for why).
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data-pvc
  namespace: paperless-lab
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-media-pvc
  namespace: paperless-lab
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
