services:
#Storage - https://github.com/minio/minio
  minio:
    image: quay.io/minio/minio
    container_name: minio
    command: server /data --console-address ":9090"
    ports:
      - "9000:9000"   # S3 API
      - "9090:9090"   # Web console
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data
      - minio-config:/root/.minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: mytravels-rabbitmq
    ports:
      - "5672:5672"      # for messaging
      - "15672:15672"    # for the management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - mqdata:/var/lib/rabbitmq
      - mqconfig:/etc/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 10s
      retries: 5
#DBs
  # https://github.com/felipewom/docker-compose-postgres
  postgres:
    image: postgres:17.6-alpine
    container_name: mytravels-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../scripts/init-dbs.sql:/docker-entrypoint-initdb.d/init-dbs.sql
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=${POSTGRES_PASSWORD} pg_isready -h localhost -p 5432 -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      
# DB Script Runner - runs after Postgres is healthy to execute custom SQL commands
  cleanup-migrations:
    image: postgres:17.6-alpine
    container_name: cleanup-migrations
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: "no"
    entrypoint: ["sh", "-c"]
    command: |
      PGPASSWORD="$$POSTGRES_PASSWORD" psql -h postgres -U "$$POSTGRES_USER" -d "$$POSTGRES_DB" <<'EOSQL'
      DO $$
      BEGIN
        IF EXISTS (
          SELECT 1 FROM information_schema.tables 
          WHERE table_schema='config' AND table_name='EFMigrationsHistory'
        ) THEN
          DELETE FROM "EFMigrationsHistory" WHERE "MigrationId" IN ('20600930075821_SeedData', '20590930075747_UpdateStoredProcedure');
        END IF;
      END
      $$;
      EOSQL
      
# Migrations
  migrate-core-db:
    image: tshepontlhokoa/mytravels-migrations:v1.0.1
    working_dir: /s/src
    entrypoint: [""]
    command: >
      sh -c "dotnet tool install --version 9.0.9 dotnet-ef &&
            dotnet ef database update --startup-project common/mytravels.migration --project common/mytravels.domain --context CoreDbContext"
    restart: "no"
    environment:
      ConnectionStrings__CoreDbContext: ${CORE_DB_CONTEXT}
    depends_on:
      postgres:
        condition: service_healthy
        
  # ASP.NET CORE API
  api:
    container_name: mytravels-api
    image: tshepontlhokoa/mytravels-api:v1.0.4
    environment:
      ConnectionStrings__CoreDbContext: ${CORE_DB_CONTEXT}
      GoogleApiKey: ${GOOGLE_API_KEY}
      GoogleMapsUrl: ${GOOGLE_MAPS_URL}
      GooglePlacesUrl: ${GOOGLE_PLACES_URL}
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: ${ASPNETCORE_URLS}
      RabbitMQ__Uri: ${RABBIT_MQ_URI}
      MinIO__Endpoint: ${MINIO_ENDPOINT}
      MinIO__AccessKey: ${MINIO_ROOT_USER}
      MinIO__SecretKey: ${MINIO_ROOT_PASSWORD}
    ports:
      - 5101:5101
    depends_on:
      rabbitmq:
        condition: service_healthy
      migrate-core-db:
        condition: service_completed_successfully

  # MESSAGING APP
  messaging:
    container_name: mytravels-messaging
    image: tshepontlhokoa/mytravels-messaging:v1.0.6
    environment:
      ConnectionStrings__CoreDbContext: ${CORE_DB_CONTEXT}
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: http://+:5102
      RabbitMQ__Uri: ${RABBIT_MQ_URI}
      MinIO__Endpoint: ${MINIO_ENDPOINT}
      MinIO__AccessKey: ${MINIO_ROOT_USER}
      MinIO__SecretKey: ${MINIO_ROOT_PASSWORD}
      GoogleApiKey: ${GOOGLE_API_KEY}
      GoogleMapsUrl: ${GOOGLE_MAPS_URL}
      GooglePlacesUrl: ${GOOGLE_PLACES_URL}
    ports:
      - 5102:5102
    depends_on:
      rabbitmq:
        condition: service_healthy
      migrate-core-db:
        condition: service_completed_successfully

  # WEB UI
  web:
    container_name: mytravels-web
    image: tshepontlhokoa/mytravels-web:v1.0.0
    ports:
      - 5100:80
    depends_on:
      - api

volumes:
  pgdata:
    driver: local
  mqdata:
    driver: local
  mqconfig:
    driver: local
  minio-data:
    driver: local
  minio-config:
    driver: local