apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: mytravels-default
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3d-mytravels-agent-2
      containers:
        - name: minio
          image: quay.io/minio/minio
          args: ["server", "/data", "--console-address", ":9090"]
          ports:
            - name: s3-api
              containerPort: 9000
              protocol: TCP
            - name: console
              containerPort: 9090
              protocol: TCP
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_ROOT_PASSWORD
          volumeMounts:
            - name: minio-data
              mountPath: /data
            - name: minio-config
              mountPath: /root/.minio
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: minio-data-pvc
        - name: minio-config
          persistentVolumeClaim:
            claimName: minio-config-pvc
