apiVersion: v1
kind: Secret
metadata:
  name: migrations-secret
  namespace: mytravels-default
type: Opaque
data:
  ConnectionStrings__CoreDbContext: SG9zdD1wb3N0Z3JlcztQb3J0PTU0MzI7RGF0YWJhc2U9Q29yZURiO1VzZXJuYW1lPXVzZXIxMjM7UGFzc3dvcmQ9cGFzc3dvcmQxMjM=
  POSTGRES_USER: dXNlcjEyMw==
  POSTGRES_PASSWORD: cGFzc3dvcmQxMjM=
  POSTGRES_DB: Q29yZURi
