apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: mytravels-default
type: Opaque
data:
  # All values must be base64-encoded: echo -n "value" | base64
  ConnectionStrings__CoreDbContext: SG9zdD1wb3N0Z3JlcztQb3J0PTU0MzI7RGF0YWJhc2U9Q29yZURiO1VzZXJuYW1lPXVzZXIxMjM7UGFzc3dvcmQ9cGFzc3dvcmQxMjM=
  RabbitMQ__Uri: YW1xcDovL3VzZXIxMjM6cGFzc3dvcmQxMjNAcmFiYml0bXE6NTY3Mg==
  MinIO__AccessKey: dXNlcjEyMw==
  MinIO__SecretKey: cGFzc3dvcmQxMjM=
