apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: paperless-lab
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
data:
  POSTGRES_USER: cGFwZXJsZXNz
  POSTGRES_PASSWORD: cGFwZXJsZXNzLWxhYi1wdw==
  POSTGRES_DB: cGFwZXJsZXNz
