apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-config
  namespace: paperless-lab
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  PAPERLESS_DBNAME: paperless
  PAPERLESS_TIME_ZONE: Africa/Johannesburg
  PAPERLESS_OCR_LANGUAGE: eng
  PAPERLESS_DBHOST: postgres
  PAPERLESS_REDIS: redis://redis:6379
  PAPERLESS_URL: http://paperless.lab.local
