apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: mytravels-default
  labels:
    app: rabbitmq
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
  namespace: mytravels-default
  labels:
    app: rabbitmq
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
    - name: management
      port: 15672
      targetPort: 15672
      protocol: TCP
