apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: paperless-lab
type: Opaque
data:
  POSTGRES_USER: cGFwZXJsZXNz
  POSTGRES_PASSWORD: cGFwZXJsZXNzLWxhYi1wdw==
  POSTGRES_DB: cGFwZXJsZXNz
